[project]
name = "e-commerce"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "faker>=40.1.2",
    "psycopg[binary]>=3.3.2",
    "python-dotenv>=1.2.1",
]
